[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'npx drizzle-kit push && NODE_ENV=production node dist/boot.js'"
healthcheckPath = "/api/trpc/ping"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
